name: Jira Event Workflow

on:
  repository_dispatch:
    types: [jira-event]

jobs:
  process_jira_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Process and Echo Jira Data
        run: |
          JIRA_DATA="${{ github.event.client_payload.jira_data }}"
          echo "Received Jira Data: $JIRA_DATA"
